productpage:
  namespace: student19-bookinfo-uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
  image: ghcr.io/patipolzaza/bookinfo-productpage
  tag: uat
ingress:
  host: sitkmutt.bookinfo.uat.opsta.net
  path: "/student19/productpage(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  RATINGS_HOSTNAME: http://sitkmutt.bookinfo.uat.opsta.net/student19/ratings
  DETAILS_HOSTNAME: http://sitkmutt.bookinfo.uat.opsta.net/student19/details
  REVIEWS_HOSTNAME: http://sitkmutt.bookinfo.uat.opsta.net/student19/reviews
  FLOOD_FACTOR: 0